### ISSUE TITLE
#5 Attributes & Hyperlinks

### ISSUE THREAD

**Issue by frankkruidhofeducom** [zoy-1998/educom-html-1727790821#5]
<p>Volg het onderdeel "Attributes &amp; Hyperlinks" en maak de opdracht.</p>
<p><a href="https://e-learning.educom.nu/essentials/HTML/attributes">https://e-learning.educom.nu/essentials/HTML/attributes</a></p>
<p>&nbsp;</p>

**Comment by zoy-1998** [comment]
Zoals je in de code kunt zien heb ik geprobeerd op paragrafen aan te brengen om de webpage beter leesbaar te maken.
Dit is echter niet gelukt. Hoe kan ik dit het beste oplossen?

**Comment by zoy-1998** [comment]
Ik heb nog een versie 2 gepushed (Exercise 5 (#5) versie 2) waarbij het wel werkt.
